@echo off
set "CC=%CONDA_BACKUP_CC%"
set "CONDA_BACKUP_CC="

set "CONDA_TOOLCHAIN_BUILD=%CONDA_BACKUP_CONDA_TOOLCHAIN_BUILD%"
set "CONDA_BACKUP_CONDA_TOOLCHAIN_BUILD="

set "CONDA_TOOLCHAIN_HOST=%CONDA_BACKUP_CONDA_TOOLCHAIN_HOST%"
set "CONDA_BACKUP_CONDA_TOOLCHAIN_HOST="
