$Env:CC=$Env:CONDA_BACKUP_CC
$Env:CONDA_BACKUP_CC=$null

$Env:CONDA_TOOLCHAIN_BUILD=$Env:CONDA_BACKUP_CONDA_TOOLCHAIN_BUILD
$Env:CONDA_BACKUP_CONDA_TOOLCHAIN_BUILD=$null

$Env:CONDA_TOOLCHAIN_HOST=$Env:CONDA_BACKUP_CONDA_TOOLCHAIN_HOST
$Env:CONDA_BACKUP_CONDA_TOOLCHAIN_HOST=$null
