travis:
  secure:
    BINSTAR_TOKEN: gb7FMyn/HkQKV0wibOhquI4YatghhMOwNp5vMpl2yxuYlDXMCk/mCsnmpQO2BFpC11Frrh0zxdh2EtWM/Gms7E+t59XF3IPs4pNWsElbJYCdFoLqJlWmzQNdQGAb9niDDqW3O/+LySILgtCsZGSQWqFCBxN0evrOGaXFdk4iGZrXLS3bDK1wOIUDwmpIAoN0TNSKLzzWzxIvCZ9cghcyxzDIvLcZVkRoRGxocsTL8HyNljKui3hkNk2szN+iqwYlPKTfV3ciD+9l7gsoquE5lNWUAKYHp2MCZTuL/YZFidrlMdOO3uBPr21krk2mPu8fOgqtuJiklA90NhBq6lOnYjlcw4r8heM2RIMvdo1u7yBmLwENoDEKH5eeZ5Koakzf/TppE1w+X5dwYoyEby3YtomYIURqsyvHizyIKfaLXAC0xwMJo9dyRjoEYlAD/oUjAkgKZKFyTbXPON/0qTPJJRTkIPXWp7KkaIu/fCvqW/HwjHrIR9Pe6AgF2Dg/KaXCgM6Sp1tG9QEAH4kGp2V46EXcXflqbW99/g0iHwqpr+8ial3zDzDvr7lqqY5Z4bbNsAetOjjq6BsP3acecMWXFCRgcUQDW/1vmW7+UtE6f4ykV/KLnOuwwR6aPk2dCTPyfIG019SOUqDsxMFtMeJRC6DY3na6M0L4MgBUnDkbkF8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

provider:
  linux_ppc64le: default
  linux_aarch64: default

conda_forge_output_validation: true
